### ISSUE TITLE
Pretraining and fine-tuning instructions

### ISSUE THREAD

**Issue by siin-lab** [mbzuai-nlp/ArTST#9]
Hi!

I was trying to finetune the model on my dataset but I couldn't understand how I should structure my dataset.   
I've performed all tasks mentioned in [data preparation](https://github.com/mbzuai-nlp/ArTST?tab=readme-ov-file#data-preparation} section (for both speech and text, and for pretraining and finetuning). I ended up with a dataset folder that looks like this:
```bash
├── audios        
├── bin_data      # generated by fairseq-preprocess
├── data.csv      # caption, audio CSV file
├── embeddings # contains speaker embeddings
├── hubert_features # generated by fairseq/examples/hubert/simple_kmeans/dump_hubert_feature.py
├── manifest.tsv            # tsv version of "data.csv"
├── processed_text.txt # transcription.txt after tokenizing it
├── tokenizer.model # generated by sentencepiece
├── tokenizer.vocab # generated by sentencepiece
├── train.tsv # generated by fairseq/examples/wav2vec/wav2vec_manifest.py script
├── transcription.txt # one audio transcription per line
└── valid.tsv # generated by fairseq/examples/wav2vec/wav2vec_manifest.py script
```
I'm now wondering how my dataset structure maps to the arguments in the [finetune.sh](https://github.com/mbzuai-nlp/ArTST/blob/main/scripts/TTS/finetune.sh) script.   
In particular these arguments:
```
DATASET=/name/of/dataset
DATA_ROOT=/TTS/_text/$DATASET
LABEL_DIR=/TTS/_labels/$DATASET
SAVE_DIR=/TTS/_models/$DATASET 
TRAIN_SET=train
VALID_SET=valid

BPE_TOKENIZER=$data_dir/
USER_DIR=./ArTST/artst
```

**Comment by djanibekov** [comment]
Please check your structure with the following example

**pre-train**
DATA_ROOT
```
├── train.tsv
├── train.bin
├── train.idx
├── valid.tsv
├── valid.bin
├── valid.idx
└── dict.txt
```

LABEL_ROOT
```
├── train.km
└── valid.km
```

**fine-tune**
```
DATA_ROOT
├──$DATASET
├─── train.tsv
├─── valid.tsv
└─── dict.txt
```

LABEL_ROOT
```
├──$DATASET
├─── train.txt
└─── valid.txt
```

**Comment by siin-lab** [comment]
Thanks for the clear response @djanibekov. Can you please elaborate on what the 
```
├── train.km
└── valid.km
``` 
files are.

In the mean time I tried to fine-tune the model, but I encountered this error (I printed the value of some variable to help debug the issue):
```
=============================================================
is_audio_input: False
len(frames): 3
frames[0].shape: torch.Size([1287, 80])
max_len: 1287
v.shape: torch.Size([1287, 80])
out.shape: torch.Size([3, 1287, 80])
v.shape: torch.Size([1257, 80])
out.shape: torch.Size([3, 1287, 80])
v.shape: torch.Size([1242, 80])
out.shape: torch.Size([3, 1287, 80])
=============================================================
is_audio_input: True
len(frames): 3
frames[0].shape: torch.Size([1, 1, 192])
max_len: 1
v.shape: torch.Size([1, 1, 192])
out.shape: torch.Size([3, 1])
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.20/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/app/models/ArTST/fairseq/fairseq_cli/train.py", line 574, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/app/models/ArTST/fairseq/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/app/models/ArTST/fairseq/fairseq_cli/train.py", line 165, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/app/models/ArTST/fairseq/fairseq/checkpoint_utils.py", line 297, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "/app/models/ArTST/fairseq/fairseq/trainer.py", line 736, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/app/models/ArTST/fairseq/fairseq/data/iterators.py", line 372, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/app/models/ArTST/ArTST/artst/data/text_to_speech_dataset.py", line 275, in collater
    spkembs = _collate_frames([s["spkembs"] for s in samples], is_audio_input=True)
  File "/app/models/ArTST/ArTST/artst/data/text_to_speech_dataset.py", line 50, in _collate_frames
    out[i, : v.size(0)] = v
RuntimeError: The expanded size of the tensor (1) must match the existing size (192) at non-singleton dimension 0.  Target sizes: [1].  Tensor sizes: [192]
```
Any idea how I should proceed?

**Comment by djanibekov** [comment]
```
├── train.km
└── valid.km
```
are pseudo labels from HuBERT

Regarding your error... Please check your speaker embedding size. I believe it should be (512, )

**Comment by siin-lab** [comment]
Thank you. The training starts without problems now.
